# Generated by Django 5.2.13 on 2026-04-14 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='device_id',
            new_name='mac_address',
        ),
        migrations.AddField(
            model_name='device',
            name='plant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.plant'),
            preserve_default=False,
        ),
    ]
