# Generated by Django 5.2.13 on 2026-04-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_device_id_device_mac_address_device_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
